### ISSUE TITLE
How can I prevent break a function call in if statement?

### ISSUE THREAD

**Issue by potatogim** [perltidy/perltidy#45] opened 2020-11-01 11:24 UTC
Hello!

First of all, I'm so grateful mongers did for what I can use perltidy :smile: 

I'm tying to use it for below code.

```perl
if (
    $self->_add_fqdn_host(
        name  => $name,
        realm => $realm
    )
    )
{
    ...
}
```

I want to format this code without `--weld-nested-containers` option like below

```perl
if ($self->_add_fqdn_host(
    name  => $name,
    realm => $realm))
{
    ...
}
```

Is there any way to do that?

or If there's none, can I implement a feature for that?

Below that is my perltidyrc file and DEBUG, LOG outputs.

```
> cat .perltidyrc 
# My .perltidyrc file

--maximum-line-length=78
--indent-columns=4
--continuation-indentation=4

--backup-and-modify-in-place
--backup-file-extension=/
--standard-error-output
--warning-output
--check-syntax

### Code Indentation Control
--nooutdent-long-lines
--closing-token-indentation=0

### Whitespace Control
--paren-tightness=2
--square-bracket-tightness=2
--brace-tightness=2
--block-brace-tightness=0
--nospace-for-semicolon
--nological-padding

### Comment Control
--indent-spaced-block-comments

### Line Break Control
--opening-brace-on-new-line
--opening-sub-brace-on-new-line
--opening-anonymous-sub-brace-on-new-line

--vertical-tightness=0
--vertical-tightness-closing=0
--block-brace-vertical-tightness=0

--want-break-before="% + - * / x != == >= <= =~ !~ < > | & = **= += *= &= <<= &&= -= /= |= >>= ||= //= .= %= ^= x= qq"
```

```
in:out indent c b  nesting   code + messages; (messages begin with >>>)
lines  levels i k            (code begins with one '.' per indent level)
------  ----- - - --------   -------------------------------------------
...
L70:70   i0:0 0 1            sub enable
L113:112 i2:3 0 0 {((        >>>Start indentation disagreement: input=2; output=3
L116:112 i1:1 0 1 {          >>>End indentation disagreement from input line 113
...
```

```
112: if ($self->_add_fqdn_host(
112: kkb{iiiiiiiiiiiiiiiiiiiii{
113: name  => $name,
113: wwwwwwb=>biiiii->LwwwwwwR,
114: realm => $realm
114: wwwwwbb=>biiiii->LwwwwwR
115: ))
115: }}
116: {
116: {
117: $self->throw_error('Failed to add FQDN host');
117: iiiiiiiiiiiiiiiiii{QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ};
118: }
118: }
```

**Comment by shancock9** [comment] 2020-11-02 15:21
If I understand correctly, you would like something which is the same as
--weld-nested but without a line break before the closing parens.  You should
be able to do that (but cannot yet) with -wn -vtc=2. The problem is that 
the -wn and -vtc=n options were implemented very differently and are
not coupled together.  I will look into fixing that.

**Comment by shancock9** [comment] 2020-11-05 23:59
The parameters -wn and -vtc=n are working correctly together now.  A test version with the update is 20201001.03 at

https://github.com/perltidy/perltidy/releases

So using the combination -wn -vtc=1 or -wn -vtc=2 should give the result you wanted.

**Comment by potatogim** [comment] 2020-11-09 06:20
> The parameters -wn and -vtc=n are working correctly together now. A test version with the update is 20201001.03 at
> 
> https://github.com/perltidy/perltidy/releases
> 
> So using the combination -wn -vtc=1 or -wn -vtc=2 should give the result you wanted.

Wow! Thanks for your feedback!

I will test it ASAP :smile: 

One more question, Can I specify weld-nested style for only some statements such as `if/while/...`?

```perl
if (_add_fqdn_host(
    name => ...,
    fqdn   => ...))
{
    ...
}

my $rv = _remove_fqdn_host(
    fqdn => ...,
);
```

**Comment by shancock9** [comment] 2020-11-09 14:59
Right now there is no control like that. It would not be hard to add one except that there are so many possibilities to include in a control: i.e. either want or don't want welding for each container type '(' '[' '{', and perhaps controlling if only parens can weld to parens, and so on.  So I may be able to eventually add something like this but designing a control will take some time.

**Comment by shancock9** [comment] 2020-12-03 14:15
Version 20201202 has been released and has a flag -wnxl which gives some control on what is welded. 
For example the following would only weld parens, and only if the first began with a keyword.

-wn -wnxl='^K(  [  {'

**Closed** 2020-12-03 14:14 UTC

**Comment by potatogim** [comment] 2020-12-04 04:26
> Version 20201202 has been released and has a flag -wnxl which gives some control on what is welded.
> For example the following would only weld parens, and only if the first began with a keyword.
> 
> -wn -wnxl='^K( [ {'

Thanks for accepting the feedback :)

If you don't mind, Could you let me know what commit is for this feature?

I'd like to help improve perltidy :)

**Comment by shancock9** [comment] 2020-12-04 13:57
An initial update was added in 2e642d2, 11 Nov 2020.  It was extended in 8e528e3, 20 Nov 2020, to add more options.  It is somewhat unusual in that the user has to say what he/she does NOT want, but that was the cleanest way to add it.  

The update is quite straightforward. It connects with the existing logic at a point where, during welding, there is an existing flag named '$do_not_weld' which can be set to prevent a weld.  So this update just looks at the surrounding tokens and user preferences and sets that flag if appropriate.
