### ISSUE TITLE
List element alignment

### ISSUE THREAD

**Issue by grimdug** [perltidy/perltidy#129] opened 2024-01-03 09:47 UTC
Is there a way to control the alignment of elements/cells within lists? Default seems to be left which looks odd on numbers only lists e.g.

```
my @t1 = (
    28,  -121, -78, 90,  64,  -61, 62, -21, -55,  -92, 127, 13,
    52,  117,  -91, 39,  -88, 48,  15, 100, -101, -83, 54,  5,
    -40, -108, 66,  -41, 109, -22, 99, 111, 106,  83,  -67, 84,
);
```

**Comment by shancock9** [comment] 2024-01-03 15:57
The only option is to format the list the way you prefer and enclose it in format-skipping comments, for example:

```
#<<<
my @t1 = (
     28,  -121, -78,  90,  64,  -61, 62, -21,  -55, -92, 127, 13,
     52,   117, -91,  39, -88,   48, 15, 100, -101, -83,  54,  5,
    -40,  -108,  66, -41, 109,  -22, 99, 111,  106,  83, -67, 84,
);
#>>>
```

In this particular case the formatting is visually improved. But in general, there are some problems with formatting this way. 
One is that the indentation scheme is be broken. For example, instead of

```
my @random = (    #
    10_000,
    1,
    10,
    1_000_000,
    100,
    1_000_000_000,
    1_000,
    100_000,
    100_000_000,
    10_000_000,
);
```

we would have

```
my @random = (    #
           10_000,
                1,
               10,
        1_000_000,
              100,
    1_000_000_000,
            1_000,
          100_000,
      100_000_000,
       10_000_000,
);
```

which, to someone scanning a script, might not look so good.

Another problem is that the introduction of a single inhomogeneous (non-integer) element would cause the formatting of a large list to switch, which is undesirable.

Attempting to automate this as an option would almost surely introduce formatting instabilities when formatting came 
under stress. The problem is that this method makes alignment depend on the list content. So some switching back
and forth will occur when formatting comes under stress, for example  due to hitting the line length limit. Such
instabilities are very difficult to avoid and to fix.

So the only option is to use format-skipping comments.

**Comment by shancock9** [comment] 2024-01-22 15:21
A new option **--valign-signed-numbers**, or **-vsn**, will be available in the next release to CPAN which can improve the
formatting of lists like this. It adds a single space, where possible, to unsigned numbers.  On the example above the result is

```
# perltidy  -vsn
my @t1 = (
     28, -121, -78,  90,  64, -61, 62, -21, -55,  -92, 127, 13,
     52,  117, -91,  39, -88,  48, 15, 100, -101, -83,  54, 5,
    -40, -108,  66, -41, 109, -22, 99, 111,  106,  83, -67, 84,
);
```

This option is in [tagged version 20230912.13](https://github.com/perltidy/perltidy/tags). The next CPAN release should be within a couple of weeks.

**Comment by shancock9** [comment] 2024-02-01 18:48
CPAN version 20240202 has been released with this flag. It will probably be the default in the following release, but for now the -vsn flag is needed to make it work. I'll close this for now; re-open it if there are any issues.

**Closed** 2024-02-01 18:48 UTC
