### ISSUE TITLE
Feature request: New switch so "-lp" is based on contents after paren.

### ISSUE THREAD

**Issue by bmartin** [perltidy/perltidy#56] opened 2021-03-18 19:06 UTC
Consider the following example comparing -lp and without .

```perl
 # -nlp looks awkward for simple arguments
 my $var = Function($foo, $bar,
     $baz);

 # -nlp looks good with an anonymous code ref:
 my $var = Function(
     $foo,
     sub {
         my ($string) = @_;
         $string =~ s/Foo/Bar/g;
         return $string;
     },
     $baz);

 # -lp looks good for simple arguments
 my $var = Function($foo, $bar,
                    $baz);

 # -lp looks bad with an anonymous code ref:
 my $var = Function($foo,
                    sub {
                        my ($string) = @_;
                        $string =~ s/Foo/Bar/g;
                        return $string;
                    },
                    $baz);
```

Currently, my team uses "--no-line-up-parenthesis" because the inline code ref case is just too painful. This makes some people grumpy because of the behavior for short simple functions.

I'm hoping to find a compromise that can satisfy everybody. I'd like a rule like "-lp" if there are parameters after the open paren and like "-nolp" if there are not. Thus the goal behavior is:

```perl
 # Acts like -lp because arguments are after "("
 my $var = Function($foo, $bar,
                    $baz);

 # Acts like -nolp because there is a newline right after "("
 my $var = Function(
     $foo,
     sub {
         my ($string) = @_;
         $string =~ s/Foo/Bar/g;
         return $string;
     },
     $baz);
```

Clang-format accidentally supports this behavior if you add a comment after the "(".

I would be happy to write a pull request if this makes sense to add.

Thanks!

**Comment by shancock9** [comment] 2021-03-19 00:54
I'll look at this.  Adding controls which are based on what is in the input
stream can introduce problems with interactions with other parameters, but a
simple fix might be to turn off -lp for any container which contains a
multi-line code block.

**Comment by bmartin** [comment] 2021-03-19 14:44
Thanks for considering. I should say that anonymous subs are the most egregious, but any time a function has lots of arguments it can make sense. Simple cases like call a very long subroutine with several arguments. More complicated is calling a constructor with an anonymous hash ref.

```perl
my $o = very::long::class::name->new(
    {
        propA => "a",
        propB => "b",
        propC => "c",
    }
);
```

If it could possibly use continuing indentation if there is nothing after "(" and otherwise indent to the paren, that would give that little bit of control needed to keep code readable.

My colleagues who like paren-aligned style are happy to create a ton of temporary variables like the below example, but it seems like a lot of extra work and risk since more code has access to `%args` than need to.

```perl
my %args = (
               propA => "a",
               propB => "b",
               propC => "c",
           );
my $o = very::long::class::name->new(\%args);
```

**Comment by shancock9** [comment] 2021-03-19 14:59
It would help if you could show what parameters you use. If there were a control based on what follows an opening paren then the -boc (break on old commas) flag would have to be set to keep formatting stable.

**Comment by shancock9** [comment] 2021-03-24 15:08
I looked at this issue and was not able to reproduce the first example.  The result of applying perltidy to this example, with and without -lp, are identical:

```
my $var = Function(
    $foo,
    sub {
        my ($string) = @_;
        $string =~ s/Foo/Bar/g;
        return $string;
    },
    $baz
);
```

So perltidy already seems to be doing what is being requested (turning off -lp) in this case.  I got the same result going back to versions as early as 2012.

But I can reproduce the second example, and in general I agree that it would be useful to have a control on the -lp formatting style.

So I've written a tentative update to help.  The basic problem is to add a control on the types of containers to which the -lp style of formatting is applied.  The main challenge is to write such a control in terms of properties which are invariant under formatting, because otherwise subtle formatting instabilities will invariably be introduced which are very difficult to find and fix. A model for doing this already exists in the -wnxl flag which controls the -wn flag, so I wrote something similar for the -lp flag.

I haven't documented it yet, but a new flag -lpxl=s would give control over the container token types to which -lp applies (braces, brackets, parentheses) much like -wnxl=s gives control over -wn.  For each of these, the contents may be restricted to a simple list without sublist.  (Note: for formatting purposes, a list is a container with a comma or wide comma. So a single item without a comma is not a list). It may be further restricted to a simple list without code blocks or ternary operators.  It may also be restricted to parentheses which indicate function call, or which follow a keyword, or both.

To make things simple I added a shortcut flag -lfp, or --line-up-function-parentheses, for the most restrictive case, which restricts -lp formatting to a function call with a simple list without code blocks or ternaries.  I think this best matches the requested update, but it could be modified if necessary.  If this looks useful I can implement it.

A few examples applying 'perltidy -lfp' are 

```
# -lp on: function call
my $loanlength = getLoanLength(
                                $borrower->{'categorycode'},
                                $iteminformation->{'itemtype'},
                                $borrower->{'branchcode'}
);
```

```
# -lp on: function call. Note that a '.' or other binary operator is not checked
( $tagfield, $subfield ) =
  MARCfind_marc_from_kohafield( "", $kohatable . "." . $kohafield,
                                $frameworkcode );
```

```
# -lp on: simple function, no sublist
$main->Button( -text    => "Click Here For Registration Form",
               -command => \&register );
```

```
# -lp off: more than one level deep
my $o = very::long::class::name->new(
    {
        propA => "a",
        propB => "b",
        propC => "c",
    }
);
```

```
# -lp off: function call contains a sublist
debug(
      "Connecting to DB.",
      "Extra-Parameters: " . join("<->", $extra_parms),
      "Config: " . join("<->", %config)
     );
```

```
# -lp off: not a function call
%blastparam = (
    -run            => \%runparam,
    -file           => '',
    -parse          => 1,
    -signif         => 1e-5,
);
```

```
# -lp off: has code block
my $var = Function(
    $foo,
    sub {
        my ($string) = @_;
        $string =~ s/Foo/Bar/g;
        return $string;
    },
    $baz
);
```

```
# -lp off: ternary in list
return
  OptArgs2::Result->usage(
    $style == OptArgs2::STYLE_FULL ? 'FullUsage' : 'NormalUsage',
    'usage: ' . $usage . "\n" );
```

```
# -lp off: 'local' is a keyword, not a user function
    local (
        $len,    $pts,      @colspec, $char, $cols,
        $repeat, $celldata, $at_text, $after_text
    );
```

**Comment by shancock9** [comment] 2021-04-02 00:06
Version 20210402 has been released with a new flag '-lpxl=s', or --line-up-parentheses-exclusion-list=s, which can restrict what gets the -lp style.  I suggest trying

-lpxl = '[ { F(2'

which will limit -lp to just simple function calls.  I have called this an 'experimental' flag for now, just in case we need to modify it .

**Closed by shancock9** 2021-04-02 00:06 UTC

**Comment by Sadrak** [comment] 2021-04-07 09:44
I tried to play with this flags, but can't get `-lfp` running:

```
Unknown option: lfp
Error in this config file: /home/ostmann/.perltidyrc
Use -npro to ignore this file, -h for help'
```

`-lpxl` works as expected ... i don't see why `-lfp` did not work ...

**Comment by shancock9** [comment] 2021-04-07 12:54
The flag -lfp was under consideration as an alias for -lp -lpxl='[ { F(2' but was not implemented in the latest release, and it is not in the manual.  The reason is that it is not yet clear if this particular selection for -lpxl is the best choice for use in a common abbreviation.

**Comment by Sadrak** [comment] 2021-04-07 13:11
sorry! I only clicked & read the commit "Add flags -lpxl=s and simplified form -lfp, requested in git #56" and did not read further.
