### ISSUE TITLE
Extra whitespace for some keyword opening parens

### ISSUE THREAD

**Issue by jooola** [perltidy/perltidy#26] opened 2020-05-23 20:25 UTC
Hi, I've been reading the man for perltidy but didn't find a way to achieve what I wanted.

I'd like to add white space within the outer-most parens of **some** keywords (if, elseif, while), but keep the horizontal tightness to 2.

I'd like something like this
```perl
if ( (1 + 1) * 3 == 6 )
# ...
while ( something($ok) )
```

instead of :
```perl
if ((1 + 1) * 3 == 6)
# ...
while (something($ok))
```

Is this doable without too much hassle ?

**Comment by shancock9** [comment] 2020-05-24 01:35
Hi Jonas,

The main difficulty is coming up with the control flags and being careful that they are sufficiently general and do not to interfere with other flags.  The simplest might be something like

-kpit or --keyword-paren-inner-tightness = 0,1,2
-kpitl or --keyword-paren-inner-tightness-list

where

-kpit=0 =>always space on inside of opening and closing parens of selected keywords
-kpit=1 =>this option not used [default]
-kpit=2 =>never space on inside of openiing and closing parens

This would have priority over all other tightness controls.

-kpitl="if while ..." is a list of keywords to which this applies, with some reasonable default


This might be okay, but there are some things to worry about:

-This assumes that the inside space of an opening and closing paren would be the same (balanced). That seems reasonable, but would anyone ever want the inside space of the opening paren to be different from the inside space of the closing paren?  I think most people like things balanced, so probably not.

-Would anyone ever want to have parens for some keywords tight and others not tight?  If so, it would be necessary to have two different lists of keywords, one for each option. 

I will think about it a bit.

**Comment by jooola** [comment] 2020-05-24 08:56
@shancock9 Thanks you for this quick answer, so what I understand is that it hasn't been implemented yet right ?

What you explained is exactly what I'm looking for. I'll freeze the white spaces for now and wait for this.

**Comment by shancock9** [comment] 2020-05-24 14:05
Right, there is no way to do this at present.  I wrote a prototype version which works, but I still need to think about the control parameters. I can add this for the next release, which should be within a few weeks.

**Comment by jooola** [comment] 2020-05-24 14:29
Nice, thanks a lot! I'll wait for this new release!

**Comment by jooola** [comment] 2020-06-01 13:52
We have been using pre-commit to run perltidy on our code, so we are able to use this feature directly from master.

Thanks for you time ! I appreciate your reactivity !

:beers:

**Comment by shancock9** [comment] 2020-06-01 19:36
Thanks, I will take a look at the latest kpit problems.
Steve

**Comment by jooola** [comment] 2020-06-01 20:51
References:
- https://github.com/backuppc/backuppc/pull/334#discussion_r433407394
- https://github.com/backuppc/backuppc/pull/334#discussion_r433408566

Sorry for not reopening the ticket here, forgot to do this.

**Comment by shancock9** [comment] 2020-06-02 00:20
I've pushed an update to fix perltidy for the issues you discovered.

A space was lost after a 'while' if the next line began with a logical operator
(|| in the case below). This triggers a padding operation which tries to adjust
space to get variables to vertically align.  It turned out to take the space
away if the keyword was 'while'.  I wrote a patch to skip this operation if
the -kpit flag is set. I may eventually skip it in all cases.

while ( $CmdJob eq "" && @CmdQueue > 0 && $RunNightlyWhenIdle != 1
    || @CmdQueue > 0
    && $RunNightlyWhenIdle == 2
    && $bpc->isAdminJob( $CmdQueue[0]->{host} ) )
{
    ...
}

The other problem was for the 'foreach' keyword.  The problem is that
this keyword might be separated from its opening paren by a variable,
and I hadn't included that possibility. I wrote a fix for that.

If you encounter any other issues let me know.

**Comment by jooola** [comment] 2020-06-02 09:48
@shancock9 I tested the fixes and works like a charm.

I found another one https://github.com/backuppc/backuppc/pull/334#discussion_r433753571

I'll try to find any remaining bugs left.

**Comment by shancock9** [comment] 2020-06-02 14:24
Yes, I forgot that 'for' can be used that way. I will at 'for' to the 'foreach' fix. I will push a new version later today.  Send any more issues you find. Thanks.

**Comment by shancock9** [comment] 2020-06-19 14:41
perltidy v20200619 is released with the 'kpit' parameter, so I will close this issue.

**Closed** 2020-06-19 14:40 UTC
