### ISSUE TITLE
try/catch as sub ending in semicolon is missing indentation

### ISSUE THREAD

**Issue by zweiter** [perltidy/perltidy#40] opened 2020-10-01 09:38 UTC
With `try` everything is fine, but the `catch` block isn't indented as expected, when there's a semicolon at the end.

`echo e 'try{ \n die ;} catch{ \n die;};' | perltidy --brace-left-and-indent --brace-left-and-indent-list="*"`
```perl
try
    {
    die ;
    }
catch
    {
    die ;
} ;
#<<< Expected
try
    {
    die ;
    }
catch
    {
    die ;
    } ;
#>>>
```
Even if you put a (very unnatural) semicolon after the `try` block it still uses the expected indentation.
`echo -e 'try{ \n die ;} ; catch{ \n die;};' | perltidy --brace-left-and-indent --brace-left-and-indent-list="*"`
```perl
try
    {
    die ;
    } ;
catch
    {
    die ;
} ;
```

**Comment by shancock9** [comment] 2020-10-01 13:35
I'll fix it. The problem is a conflict with a rule about lines ending in semicolons.

**Comment by shancock9** [comment] 2020-12-03 14:03
version 20201202 has been released with a fix for this problem.

**Closed by shancock9** 2020-12-03 14:03 UTC
