### ISSUE TITLE
vertical alignment issues

### ISSUE THREAD

**Issue by pukku** [perltidy/perltidy#25] opened 2020-05-11 20:47 UTC
Hi! I have a very wide array of hashes that I'm working on, and perltidy breaks the vertical alignment. Is there anything I can do to fix this?

Here is the (nicely formatted) version (the actual array is about 450 hashes, so I'm only giving you a representative section):

```perl
my $mapping = [
# ...
    { 'is_col' => 'dsstdat',                      'cr_col' => 'enroll_isaric_date',         'trans' => 0, },
    { 'is_col' => 'corona_ieorres',               'cr_col' => '',                           'trans' => 0, },
    { 'is_col' => 'symptoms_fever',               'cr_col' => 'elig_fever',                 'trans' => 1, 'manually_reviewed' => '@TODO', 'map' => { '0' => '0', '1' => '1', '9' => '@TODO' }, },
    { 'is_col' => 'symptoms_cough',               'cr_col' => 'elig_cough',                 'trans' => 1, 'manually_reviewed' => '@TODO', 'map' => { '0' => '0', '1' => '1', '9' => '@TODO' }, },
    { 'is_col' => 'symptoms_dys_tachy_noea',      'cr_col' => 'elig_dyspnea',               'trans' => 1, 'manually_reviewed' => '@TODO', 'map' => { '0' => '0', '1' => '1', '9' => '@TODO' }, },
    { 'is_col' => 'symptoms_clinical_susp',       'cr_col' => 'elig_ari',                   'trans' => 0, },
    { 'is_col' => 'sex',                          'cr_col' => 'sex',                        'trans' => 1, 'manually_reviewed' => 1, 'map' => { '0' => '1', '1' => '2' }, },
    { 'is_col' => 'age',                          'cr_col' => '',                           'trans' => 0, },
    { 'is_col' => 'ageu',                         'cr_col' => '',                           'trans' => 0, },
# ...
];
```

But when I run perltidy on the same section, it does this:

```perl
my $mapping = [
# ...
    { 'is_col' => 'dsstdat',                 'cr_col' => 'enroll_isaric_date', 'trans' => 0, },
    { 'is_col' => 'corona_ieorres',          'cr_col' => '',                   'trans' => 0, },
    { 'is_col' => 'symptoms_fever',          'cr_col' => 'elig_fever',         'trans' => 1, 'manually_reviewed' => '@TODO', 'map' => { '0' => '0', '1' => '1', '9' => '@TODO' }, },
    { 'is_col' => 'symptoms_cough',          'cr_col' => 'elig_cough',         'trans' => 1, 'manually_reviewed' => '@TODO', 'map' => { '0' => '0', '1' => '1', '9' => '@TODO' }, },
    { 'is_col' => 'symptoms_dys_tachy_noea', 'cr_col' => 'elig_dyspnea',       'trans' => 1, 'manually_reviewed' => '@TODO', 'map' => { '0' => '0', '1' => '1', '9' => '@TODO' }, },
    { 'is_col' => 'symptoms_clinical_susp',  'cr_col' => 'elig_ari',           'trans' => 0, },
    { 'is_col' => 'sex', 'cr_col' => 'sex', 'trans' => 1, 'manually_reviewed' => 1, 'map' => { '0' => '1', '1' => '2' }, },
    { 'is_col' => 'age', 'cr_col' => '', 'trans' => 0, },
    { 'is_col' => 'ageu',                   'cr_col' => '',                       'trans' => 0, },
# ...
];
```

What I don't understand is why those lines in the middle don't line up, but then it goes back and does line up, and then stops lining up again?

I'm using the following settings:

```perl
'--noprofile',                           # ignore a .perltidyrc; all settings come from this file
'--quiet',                               # don't mess things up if something goes wrong
'--indent-columns=4',                    # use 4 columns for a tab stop
'--maximum-line-length=0',               # I will take care about splitting lines where I want them...
'--extended-syntax',                     # allow some extended syntaxes to be valid
'--character-encoding=utf8',             # make perltidy treat multi-byte characters correctly
'--no-outdent-long-quotes',              # long quotes should not be outdented, even if they exceed line length
'--square-bracket-tightness=0',          # I like single items in square brackets to have spaces
'--add-semicolons',                      # make sure all blocks are terminated by a semi-colon
'--trim-pod',                            # remove any whitespace from the ends of POD lines
'--no-outdent-long-comments',            # leave long comment lines alone
'--ignore-side-comment-lengths',         # don't include the length of the comments in the line length
'--static-block-comments',               # let comments starting with `##` not have an extra line put in front (this is the default)
'--static-side-comments',                # let line-ending comments starting with `##` not be aligned with other comments
'--format-skipping-begin=#+<<<',         # allow multiple pound signs for format skipping
'--format-skipping-end=#+>>>',           # ditto to end format skipping
'--stack-opening-tokens',                # I prefer opening tokens to be inline
'--stack-closing-tokens',                # stack closing tokens, instead of putting them on separate lines
'--no-delete-old-newlines',              # keep newlines that have been created by the programmer
'--break-at-old-method-breakpoints',     # keep breaks before -> characters, so that method chains look nice
'--break-at-old-ternary-breakpoints',    # keep any special ternary breaks
'--keep-interior-semicolons',            # there's usually a really good reason for multiple commands on one line
'--keep-old-blank-lines=1',              # but don't allow more than one blank line
'--one-line-block-nesting=1',            # keep one-line blocks if I've written such (maybe I shouldn't do this...)
```

Many thanks,
Ricky

**Comment by shancock9** [comment] 2020-05-11 23:27
Hi Ricky,
The problem is that this exceeds the ability of the vertical alignment logic.  Basically,
the logic looks for two or more lines a common pattern (including number of things to align) and
then keeps going until the pattern is broken.  Then it starts over.

So in this case, each line which includes a 'manually_reviewed' term is considered a
change in pattern, so the alignment gets broken.  So if all lines had the 'manually_reviewed'
data everything would align.  When it makes a variable appearance though the
algorithm gives up.  The only control on vertical alignment
that the user has is to insert blank lines to force a break in alignment.

It's funny how a human can look at this and immediately see what the overall pattern is,
whereas when you try to code a general algorithm it can get tricky.  In this particular
case though I have an idea on how to fix it and I will look into it.  

It would help to have a larger example; would it be possible for you to email
me something larger?  (perltidy at users dot sourceforge dot net).  Or can I
assume that the larger data set is more or less like this?
Steve

**Comment by pukku** [comment] 2020-05-11 23:53
Thanks! Part of what confuses me is that in the larger block of code, it isn’t consistent about what breaks it; sometimes it breaks in the middle of a section that doesn’t have much change, and sometimes it works; it isn’t always the ‘manually_reviewed’ key that causes it.

I will send the entire $mapping assignment. I have slightly obfuscated the text of the column names (not the key names), but it still breaks in the various ways the real one does.

I appreciate you looking at it. For now, I will use the ‘#<<<‘ comment to hide it from Perltidy, but I will keep my fingers crossed…

Many thanks,
Ricky

**Comment by shancock9** [comment] 2020-05-24 14:29
I have added a fix for this which will be in the next release. I think that should be within a few weeks.
Steve

**Comment by pukku** [comment] 2020-05-25 03:15
Many thanks! I look forward to it (it will really help)!

Ricky

**Comment by shancock9** [comment] 2020-06-19 14:36
perltidy v20200619 has a fix for this type of problem

**Closed** 2020-06-19 14:35 UTC

**Comment by pukku** [comment] 2020-06-19 14:38
Thanks! I will update and check it out!
