### ISSUE TITLE
-lp with side comment or line break reverts to default method

### ISSUE THREAD

**Issue by zweiter** [perltidy/perltidy#64] opened 2021-04-28 13:10 UTC
As you've written in the [docs on CPAN](https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy#List-indentation-using-lp,-line-up-parentheses)
> Also, the existence of line breaks and/or block comments between the opening and closing parens may cause perltidy to temporarily revert to its default method.

This is how it looks correctly (with `-lp`)
```perl
$object->method(
                 'Do something',
                 $self->my_id,
                 {
                    "my_attr" => 1,
                 }
);
```
With the comment it reverts to not `-lp`
```perl
$object->method(
    'Do something',
    $self->my_id,
    {
      "my_attr" => 1,    # explains this attr
    }
);
```

**Comment by shancock9** [comment] 2021-04-30 12:32
The wording regarding when -lp reverts to the default indentation scheme
has been revised to include side comments as follows:

In situations where perltidy does not have complete freedom to choose line
breaks it may temporarily revert to its default indentation method.  This can
occur for example if there are blank lines, block comments, multi-line quotes,
or side comments between the opening and closing parens, braces, or brackets.

**Comment by shancock9** [comment] 2021-04-30 14:01
I'll look at it, but it is a complicated issue.

**Comment by shancock9** [comment] 2021-11-21 02:13
The next release to CPAN, which may be a few months away, will have a new flag -xlp (--extended-line-up-parentheses) which will remove the limitations on the -lp format in which it reverts to standard formatting at side comments, blank lines, and broken code blocks.  This new flag -xlp is off by default, to avoid changing existing formatting, so you need to set this flag to activate this feature.  

The main issue that I have noticed with this new flag is that the maximum line length can be sometimes be exceeded for deeply nested code, and code with very long identifiers or quotes.  I will see if I can minimize this problem.  But this has always been a problem with the -lp format, and it can be controlled somewhat by using a long maximum line length, and perhaps adding the -iscl flag (--ignore-side-comment-lengths) if there are very long side comments.

If anyone wants to test it, the interim tagged version 20211029.01 at github has the update:

https://github.com/perltidy/perltidy/releases/tag/20211029.01

**Comment by ecos-platypus** [comment] 2021-11-25 09:16
Thank you again for the extended line-up parentheses mode! With version 20211029.01, the issue regarding side comments is resolved. The line break handling is improved, we only encounter an issue with function calls whose return value is stored in a variable. Without the variable assignment, the alignment works as expected.

The issue only occurs with `--break-before-paren=2` and `--break-before-paren=3`.

#### Without variable assignments

```
$self -> test_call (
                    $arg1,
                    $arg2

                   ) ;

$self -> test_call (
                    $arg1,
                    $arg2

                   ) ;

$self -> test_call (

                    $arg1,
                    $arg2

                   ) ;
```

#### With variable assignments

```
my $test_var = $self -> test_call (
                        $arg1,
                        $arg2

                                  ) ;

my $test_var = $self -> test_call (
                        $arg1,
                        $arg2

                                  ) ;

my $test_var = $self -> test_call (

                        $arg1,
                        $arg2

) ;
```

#### Relevant configuration options

```
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Basic Options
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--maximum-line-length=120
--output-line-ending="unix"
--iterations=2

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Code Indentation Control
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--continuation-indentation=4
--line-up-parentheses
--extended-line-up-parentheses
--closing-token-indentation=1

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Whitespace Control
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--all-containers-tightness=2
--space-terminal-semicolon
--want-left-space="= -> ( )"
--want-right-space="= -> ( )"
--space-keyword-paren
--space-function-paren
--no-function-paren-vertical-alignment

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Line Break Control
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--brace-left-and-indent
--brace-left-and-indent-list="*"
--break-before-hash-brace=3
--break-before-square-bracket=3
--break-before-paren=3
```

**Comment by shancock9** [comment] 2021-11-26 15:15
Thanks for catching that. Some needless old code involving the -bbp flag was causing the problem.  An updated tagged version 0.2 with the correction is at

https://github.com/perltidy/perltidy/releases/tag/20211029.02

I will be making more updates over the next few months to improve how very long or deeply nested code gets handled as it reaches and exceeds the line length limit.

**Comment by ecos-platypus** [comment] 2021-11-29 12:32
Thank you for the update. The issue with variable assignments is fixed. However, there seems to be a regression regarding variable assignments of multi-line hashs with side comments. The examples were formatted with the configuration options included in my last comment:

Old & expected behavior:
```
our %hash =
    (
     hash_ref =>    # side commect
         {
          key1 => val1,
          key2 => val2,
          key3 => val3,
         },
    ) ;
```

New behavior:

```
our %hash =
    (
             hash_ref =>    # side commect
                 {
                  key1 => val1,
                  key2 => val2,
                  key3 => val3,
                 },
    ) ;
```

**Comment by shancock9** [comment] 2021-11-29 14:03
This works in the currently development version, which I tagged as .03 at

https://github.com/perltidy/perltidy/tags


But a variation which does not yet work correctly is when there is a blank after the
opening paren, like this input:

our %hash =
    (

     hash_ref =>    # side commect
         {
          key1 => val1,
          key2 => val2,
          key3 => val3,
         },
    ) ;

What's going on is that the information that there is a break after the '=' is not currently being propagated past the blank line.  So the remainder of the text is outdented as if the opening paren followed on the same line as the =.  This will be corrected soon.

**Comment by shancock9** [comment] 2022-02-19 14:47
Version 20220217 has been released with the `-xlp` flag.  I've done a lot of testing and it seems to be working well.  The man page has been updated and is worth reviewing.  I'll close this issue, but go ahead and re-open it if problems are found.

**Closed** 2022-02-19 14:48 UTC
